services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Abcd1234
      MYSQL_DATABASE: instagram
      MYSQL_USER: instagram
      MYSQL_PASSWORD: Abcd1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}