server:
  port:8081
spring:
  application:
    name: instagram
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
#  flyway:
#    create-schemas: true
#    baseline-on-migrate: true
#    url: jdbc:mysql://localhost:3306/instagram
#    user: instagram
#    password: Abcd1234
security:
  jwt:
    secret-key: 3aefbc1d71566416f9e995c6b7e5a9b810f05edf5a42e6d72ca692437c72eeff
    expiration-time: 3600000

